obj-$(CONFIG_TARGET_ZIXLINK_SHIELD2)    := shield2.o
obj-$(CONFIG_TARGET_ZIXLINK_SHIELD2_1)  := shield2_1.o
obj-$(CONFIG_TARGET_ZIXLINK_SHIELD2_2)  := shield2_2.o

mkimage-qspi-nor-macronix-mx25l3233f: mkimage-qspi-nor-macronix-mx25l3233f.c
	gcc $< -o $@
